language: csharp
solution: Proyecto26.RestClient.sln

before_install: cd src
 
install:
  - nuget restore Proyecto26.RestClient.sln
 
script:
  - xbuild /p:Configuration=Debug Proyecto26.RestClient.sln
